@baseURL = http://127.0.0.1:3000 

# login
POST {{baseURL}}/login HTTP/1.1
content-type: application/json
Authorization: Basic QWRtaW46cGFzc3dvcmQ=

{
  "Username": "Admin",
  "Password": "112233"
}

###

GET {{baseURL}}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZXhwIjoxNjI1OTExODIzLCJ1c2VybmFtZSI6IkFkbWluIn0.krZOfLe_WOnloBS_dc1Klls6DqSJbAfL9tMLfyZTCQ8